CREATE COLUMN TABLE "IACUBE"."CANDIDATES"(
	"ID" SMALLINT CS_INT,
	"FIRST_NAME" NVARCHAR(100),
	"SECOND_NAME" NVARCHAR(100),
	"GENDER" NVARCHAR(1),
	PRIMARY KEY (
		"ID"
	)
) UNLOAD PRIORITY 5 AUTO MERGE;

CREATE COLUMN TABLE "IACUBE"."CANDIDATES_PROFILES"(
	"CANDIDATE_ID" SMALLINT CS_INT,
	"PROFILE_ID" SMALLINT CS_INT
) UNLOAD PRIORITY 5 AUTO MERGE;

CREATE COLUMN TABLE "IACUBE"."DOCUMENTS"(
	"ID" SMALLINT CS_INT,
	"LANGUAGE" NVARCHAR(2),
	"EXT_ID" SMALLINT CS_INT,
	"EXT_TYPE" NVARCHAR(1),
	"CONTENT" NVARCHAR(5000),
	PRIMARY KEY (
		"ID"
	)
) UNLOAD PRIORITY 5 AUTO MERGE;

CREATE COLUMN TABLE "IACUBE"."DOCUMENT_SKILLS"(
	"ID" SMALLINT CS_INT,
	"LANGUAGE" NVARCHAR(2),
	"EXT_ID" SMALLINT CS_INT,
	"EXT_TYPE" NVARCHAR(1),
	"CONTENT" NVARCHAR(5000),
	PRIMARY KEY (
		"ID"
	)
) UNLOAD PRIORITY 5 AUTO MERGE;

CREATE COLUMN TABLE "IACUBE"."EXPERIENCE"(
	"PROFILE_ID" SMALLINT CS_INT,
	"COMPANY" NVARCHAR(50),
	"POSITION" NVARCHAR(50),
	"DESCRIPTION" NVARCHAR(2000),
	"START_YEAR" NVARCHAR(4),
	"START_MONTH" NVARCHAR(2),
	"END_YEAR" NVARCHAR(4),
	"END_MONTH" NVARCHAR(2)
) UNLOAD PRIORITY 5 AUTO MERGE;

CREATE COLUMN TABLE "IACUBE"."PROFILES"(
	"ID" SMALLINT CS_INT,
	"EXTERNAL_ID" NVARCHAR(50),
	"PROFILE_TYPE" NVARCHAR(1),
	"LINK" NVARCHAR(200),
	"LANGUAGE" NVARCHAR(2),
	"HEADLINE" NVARCHAR(100),
	"SUMMARY" NVARCHAR(2000),
	PRIMARY KEY (
		"ID"
	)
) UNLOAD PRIORITY 5 AUTO MERGE;

CREATE COLUMN TABLE "IACUBE"."REQUISITIONS"(
	"ID" SMALLINT CS_INT,
	"POSITION" NVARCHAR(100),
	"DESCRIPTION" NVARCHAR(2000),
	"LANGUAGE" NVARCHAR(2),
	"STATUS" NVARCHAR(1),
	PRIMARY KEY (
		"ID"
	)
) UNLOAD PRIORITY 5 AUTO MERGE;

CREATE COLUMN TABLE "IACUBE"."REQUISITION_SKILLS"(
	"REQ_ID" SMALLINT CS_INT,
	"SKILL" NVARCHAR(100),
	"WEIGHT" SMALLINT CS_INT
) UNLOAD PRIORITY 5 AUTO MERGE;

CREATE COLUMN TABLE "IACUBE"."SKILLS"(
	"PROFILE_ID" SMALLINT CS_INT,
	"SKILL" NVARCHAR(100)
) UNLOAD PRIORITY 5 AUTO MERGE;